# Generated by Django 3.1.4 on 2020-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('column_separator', models.CharField(choices=[('TAB', 'Tab'), ('SEMICOLON', 'Semicolon (;)'), ('COMMA', 'Comma (,)'), ('SPACE', 'Space')], max_length=120)),
                ('string_character', models.CharField(choices=[('DOUBLE_QUOTE', 'Double-quote (")'), ('COLONEL', "Single-quote (')")], max_length=120)),
            ],
        ),
    ]
