# Generated by Django 3.1.4 on 2020-12-30 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 11, 56, 13, 460131)),
        ),
    ]
